=== nalleon/lnd/primer-curso/unidad-07/tareas/xsd/alumno.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="alumnos">
    <xs:complexType>
 <xs:sequence>
    <xs:element ref="alumno" minOccurs="0" maxOccurs="unbounded"> </xs:element> 
    </xs:sequence>
      <xs:attribute name="grupo" type="xs:integer" use="optional" default="1"></xs:attribute>
</xs:complexType>
</xs:element>
<xs:element name="alumno">
<xs:complexType>
    <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="edad" type="tipoedad"/>
        <xs:element ref="nota" minOccurs="1" maxOccurs="10" />
        <xs:element name="telefono" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="iniciales" type="tipoiniciales"/>
    </xs:sequence>
    <xs:attribute name="dni" type="tiponombre" use="required"></xs:attribute>
    </xs:complexType>
    </xs:element>
    <xs:element name="nota">
    <xs:complexType>
    <xs:simpleContent>
    <xs:extension base="tiponota">
    <xs:attribute name="eval" type="tipoevaluacion" use="required"/>
    </xs:extension>
    </xs:simpleContent>
    </xs:complexType>
    </xs:element>
    
<xs:simpleType name="tipoevaluacion">
<xs:restriction base="xs:integer">
<xs:enumeration value="1"></xs:enumeration>
<xs:enumeration value="2"></xs:enumeration>
<xs:enumeration value="3"></xs:enumeration>
</xs:restriction>

</xs:simpleType>
<xs:simpleType name="tipodni">
<xs:restriction base="xs:string">
<xs:length value="8"></xs:length>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="tiponombre">
<xs:restriction base="xs:string">
<xs:minLength value="1"></xs:minLength>
<xs:maxLength value="12"></xs:maxLength>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="tiponota">
<xs:restriction base="xs:decimal">
<xs:fractionDigits value="2"></xs:fractionDigits>
<xs:totalDigits value="3"></xs:totalDigits>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipoedad">
<xs:restriction base="xs:decimal">
<xs:fractionDigits value="1"></xs:fractionDigits>
<xs:totalDigits value="4"></xs:totalDigits>
<xs:maxExclusive value = "120"></xs:maxExclusive>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipoiniciales">
<xs:restriction base="xs:string">
<xs:pattern value="[A-Z][A-Z][A-Z]"></xs:pattern>
</xs:restriction>
</xs:simpleType>

</xs:schema>

=== nalleon/lnd/unidad-7/tareas/xsd/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos grupo="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam/Documentos/lnd/XSD/alumno.xsd">
<alumno dni="2324323W">
<nombre> Juan </nombre>
<edad> 23</edad>
<nota eval="1"> 8.5 </nota>
<nota eval="2"> 3.4 </nota>
<nota eval="3"> 7.1  </nota>
<telefono>45678943</telefono>
<iniciales>JGG</iniciales>
</alumno>
<alumno dni="2454354P">
<nombre> Lion </nombre>
<edad> 31</edad>
<nota eval="1"> 8.5 </nota>
<nota eval="2"> 9.4 </nota>
<nota eval="3"> 9.1  </nota>
<telefono>3435345</telefono>
<telefono>2132434451</telefono>
<iniciales>LJH</iniciales>
</alumno>
</alumnos>
