<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clases[ 
 <!ELEMENT clases (clase+)>
    <!ELEMENT clase (profesor, alumnos)>
    <!ELEMENT profesor (nombre, apellidos?)>
    <!ELEMENT alumnos (alumno+)>
    <!ELEMENT alumno (nombre, apellidos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT pizarra (#PCDATA)>
    <!ATTLIST clase pizarra (Si | No) "Si">
]>
<clases>
<clase pizarra="Si">
   <profesor>
      <nombre> Juan Alberto </nombre>
     <apellidos> Tormo</apellidos>
   </profesor>
   <alumnos>
   <alumno>
     <nombre> Miriam </nombre>
     <apellidos> Saavedra </apellidos>
   </alumno>
    <alumno>
     <nombre> Sergio </nombre>
     <apellidos> Martínez</apellidos>
   </alumno>
   </alumnos>
</clase>
<clase pizarra="No">
   <profesor>
      <nombre> Elisabet S. </nombre>
   </profesor>
   <alumnos>
   <alumno>
     <nombre> Alejandro Daniel </nombre>
     <apellidos> Olmo</apellidos>
   </alumno>
   </alumnos>
</clase>
</clases>

